# Generated by Django 5.0.4 on 2026-02-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_simplify_roles_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('studio_head', 'Studio Head'), ('admin', 'Admin'), ('accounting', 'Accounting'), ('bim_specialist', 'BIM Specialist'), ('intern', 'Intern'), ('junior_architect', 'Junior Architect'), ('president', 'President'), ('site_engineer', 'Site Engineer'), ('site_coordinator', 'Site Coordinator')], max_length=50, null=True),
        ),
    ]
