# Generated by Django 5.0.4 on 2026-02-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('studio_head', 'Studio Head'), ('admin', 'Admin'), ('accounting', 'Accounting'), ('employee', 'Employee'), ('bim_specialist', 'BIM Specialist'), ('intern', 'Intern'), ('junior_architect', 'Junior Architect'), ('president', 'President'), ('site_engineer', 'Site Engineer'), ('site_coordinator', 'Site Coordinator'), ('ceo', 'CEO')], max_length=50, null=True),
        ),
    ]
