# Generated by Django 6.0.1 on 2026-03-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_accounts_cu_departm_38d9c8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('studio_head', 'Studio Head'), ('admin', 'Admin'), ('accounting', 'Accounting'), ('bim_specialist', 'BIM Specialist'), ('intern', 'Intern'), ('junior_architect', 'Junior Architect'), ('president', 'President'), ('site_engineer', 'Site Engineer'), ('site_coordinator', 'Site Coordinator'), ('ceo', 'CEO')], max_length=50, null=True),
        ),
    ]
