# Generated by Django 6.0.1 on 2026-03-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payroll_allowance_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signature_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
