# Generated by Django 5.0.4 on 2026-05-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_payroll_allowance_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('studio_head', 'Studio Head'), ('accounting', 'Accounting'), ('bim_specialist', 'BIM Specialist'), ('intern', 'Intern'), ('junior_architect', 'Junior Architect'), ('site_engineer', 'Site Engineer'), ('site_coordinator', 'Site Coordinator'), ('ceo', 'CEO')], max_length=50, null=True),
        ),
    ]
