# Generated by Django 5.0.4 on 2026-02-23 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_suggested', 'Task Suggested'), ('task_confirmed', 'Task Confirmed'), ('task_rejected', 'Task Rejected'), ('task_assigned', 'Task Assigned'), ('completion_requested', 'Completion Requested'), ('completion_confirmed', 'Completion Confirmed'), ('completion_rejected', 'Completion Rejected'), ('dept_task_suggested', 'Department Task Suggested'), ('dept_task_grabbed', 'Department Task Grabbed'), ('dept_task_completed', 'Department Task Completed'), ('dept_task_abandoned', 'Department Task Abandoned')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('department_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='todos.departmenttask')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_notifications', to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='todos.todo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
