# Generated by Django 6.0.1 on 2026-03-12 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BimDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('model-update', 'Model Update'), ('clash-detection', 'Clash Detection'), ('drawing-package', 'Drawing Package'), ('simulation', 'Simulation / Rendering'), ('bim-standards', 'BIM Standards')], max_length=50)),
                ('doc_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('studio_head_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('studio_head_comments', models.TextField(blank=True, null=True)),
                ('ceo_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ceo_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bim_docs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_ceo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ceo_docs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_studio_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_studio_head_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BimDocumentationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('model', '3D Model'), ('image', 'Image/Reference')], max_length=20)),
                ('file_path', models.CharField(help_text='Path to file in storage (Supabase, S3, etc.)', max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bim_documentation.bimdocumentation')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bimdocumentation',
            index=models.Index(fields=['created_by', 'status'], name='bim_documen_created_6e5343_idx'),
        ),
        migrations.AddIndex(
            model_name='bimdocumentation',
            index=models.Index(fields=['status'], name='bim_documen_status_7b9fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='bimdocumentation',
            index=models.Index(fields=['-created_at'], name='bim_documen_created_a26fa9_idx'),
        ),
    ]
