# Generated by Django 6.0.1 on 2026-03-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_documentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimdocumentationfile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='bim-docs/%Y/%m/%d/'),
        ),
    ]
