# Generated by Django 6.0.1 on 2026-03-12 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bim_documentation', '0002_bimdocumentationfile_uploaded_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BimDocumentationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_system_comment', models.BooleanField(default=False, help_text='Auto-posted by the system on approval/rejection actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_doc_comments', to=settings.AUTH_USER_MODEL)),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_comments', to='bim_documentation.bimdocumentation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bim_documentation.bimdocumentationcomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
