# Generated by Django 6.0.1 on 2026-03-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='requester_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
