# Generated by Django 5.0.4 on 2026-03-19 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0002_materialrequest_requester_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_system_comment', models.BooleanField(default=False, help_text='Auto-posted by the system on approval/rejection actions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_request_comments', to=settings.AUTH_USER_MODEL)),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='material_requests.materialrequest')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='material_requests.materialrequestcomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
