# Generated by Django 5.0.4 on 2026-03-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0003_materialrequestcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='request_image',
            field=models.ImageField(blank=True, null=True, upload_to='material_requests/'),
        ),
    ]
