# Generated by Django 5.0.4 on 2026-03-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0004_materialrequest_request_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='request_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
