# Generated by Django 5.0.4 on 2026-04-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0009_materialrequest_accounting_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='accounting_status',
            field=models.CharField(choices=[('pending_funds', 'Pending Funds'), ('funds_released', 'Funds Released')], default='pending_funds', max_length=30),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
