# Generated by Django 6.0.4 on 2026-04-30 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_requests', '0009_materialrequest_accounting_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='accounting_status',
            field=models.CharField(choices=[('pending_funds', 'Pending Funds'), ('funds_released', 'Funds Released')], default='pending_funds', max_length=30),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='budget_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_material_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialrequestcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_request_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
