# Generated by Django 5.0.4 on 2026-03-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_deduction_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session_type',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('overtime', 'Overtime')], max_length=20, null=True),
        ),
    ]
