# Generated by Django 5.0.4 on 2026-03-09 05:58

from django.conf import settings
from django.db import connection, migrations


def forwards(apps, schema_editor):
    table = 'attendance_attendance'
    # Drop old unique constraint if it exists
    if connection.vendor == 'postgresql':
        schema_editor.execute(
            "DROP INDEX IF EXISTS attendance_attendance_employee_id_date_cb2c479f_uniq"
        )
    elif connection.vendor == 'sqlite':
        pass  # SQLite handles unique via table rebuild
    # Create new unique constraint
    schema_editor.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS attendance_attendance_emp_date_sess_uniq "
        "ON %s (employee_id, date, session_type)" % table
    )


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_clock_in_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
