# Generated by Django 5.0.4 on 2026-03-09 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='work_doc_file_paths',
            field=models.JSONField(blank=True, default=list, help_text='List of file paths in Supabase bucket'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_doc_note',
            field=models.TextField(blank=True, help_text='Documentation note about work completed (required if files uploaded)', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_doc_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when first file was uploaded', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_doc_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_work_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
