# Generated by Django 5.0.4 on 2026-03-11 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_work_documentation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', '-date'], name='att_employee_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='att_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'status'], name='att_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date', 'session_type'], name='att_emp_date_session_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['date'], name='cal_date_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type', 'date'], name='cal_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', '-start_date'], name='leave_emp_start_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['status', '-start_date'], name='leave_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['start_date', 'end_date'], name='leave_date_range_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['employee', '-created_at'], name='ot_emp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='overtimerequest',
            index=models.Index(fields=['-date_completed'], name='ot_date_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['employee', '-timestamp'], name='timelog_emp_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['employee', 'log_type'], name='timelog_emp_type_idx'),
        ),
    ]
