# Generated by Django 5.0.4 on 2026-03-27 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_add_attendance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='attendance',
                    unique_together={('employee', 'date', 'session_type')},
                ),
            ],
            database_operations=[],
        ),
    ]
