# Generated by Django 5.0.4 on 2026-04-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimerequest',
            name='employee_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
