# Generated by Django 5.0.4 on 2026-04-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_signature_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='management_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
