# Generated by Django 5.0.4 on 2026-05-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_overtimerequest_management_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual overtime hours worked, entered manually by Accounting after completion.', max_digits=8, null=True),
        ),
    ]
